#! /bin/bash

# Title 	: 	Youtube-dl Download Manager <ydpm>
# Author	:	Sarath <sarath.hacks@gmail.com>
# Manage download urls in a file , Inspired by Bower, Composer , NPM

# Default playlist file 
DOWNLOAD_LIST_FILE=.playlist

CUR_DIR="$( cd "$( dirname "$0" )" && pwd )"

function info(){
	echo -e "\e[35m\t\tYDLM 0.0  "

	echo -e '\tYoutube-dl Download Manager'
	echo -e '\tVersion 0.0 \e[0m'
}

# Call Info
info




if [ ${#1} = 0 ]
	then
	echo "Nothing as parameter"
else
	# check a command
	
	#if not command
	  # check the url already exists
	echo $1 >> .playlist
fi


if [ "$( which youtube-dl )"  = "" ]; then
	# Omit a Std Error message
	>&2 echo -e "\e[1;31mError : youtube-dl not installed in you system\e[0m";
	exit 1;
fi
# Check the file exists in the folder 
if [ -f "$DOWNLOAD_LIST_FILE" ]; then
	echo -e "Download list file loaded";
	#Execute youtube-dl command
	youtube-dl -a $DOWNLOAD_LIST_FILE
else
	echo -e "\e[31mDownload list file not found :(\e[0m";
fi